package websocket

import (
	"encoding/json"
)

func (e *Event) Unmarshal(b []byte) error {
	return json.Unmarshal(b, e)
}

// Generated by https://quicktype.io
type Event struct {
	Event string            `json:"event"`
	Code  string            `json:"code"`
	Arg   map[string]string `json:"arg"`
	Msg   string            `json:"msg"`
}

type Arg struct {
	Channel string `json:"channel"`
	InstID  string `json:"instId"`
}

// Generated by https://quicktype.io

type Op struct {
	Op   string              `json:"op"`
	Args []map[string]string `json:"args"`
}

// Generated by https://quicktype.io

type CandleType struct {
	Arg  Arg        `json:"arg"`
	Data [][]string `json:"data"`
}
